# Generated by Django 5.0.6 on 2024-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avtor', models.CharField(max_length=255)),
                ('narx', models.IntegerField(max_length=255)),
                ('rasm', models.FileField(upload_to='photo')),
            ],
        ),
    ]
